### ISSUE TITLE
Menu -> Submenu positioning issues.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#962] opened 2021-03-15 14:36 UTC
The dropdown-submenu dropdown-item menu-item is not styled properly 
Example in this case is "What We Do" menu item.
Left Margin needs set properly.
padding needed to center text and create height.
svg arrow needs to be positioned within the box.

![image](https://user-images.githubusercontent.com/6786299/111170413-e71a6f00-8571-11eb-990e-00e31b9e637b.png)

**Comment by meetmandeep** [comment] 2021-03-15 21:41
This looks like a duplicate of #948 which was recently resolved.

**Closed as completed** 2021-03-23 03:04 UTC

**Comment by Gaganbird** [comment] 2021-03-23 03:06
It has been resolved in #948
