### ISSUE TITLE
Add 'nav' as a section type.

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1452] opened 2021-06-17 17:06 UTC
I couldn't figure out how to reopen #1450, so I made a new issue.

The reason I can't use the Menu block is because I don't want the links auto-populated from the site's pages.

I have a hard-coded list of hyperlinks and I would like to use the proper HTML semantic tag of `<nav>`.  

Is that possible?

**Comment by meetmandeep** [comment] 2021-06-17 18:06
@mathisjay closing this duplicate of #1450 which I've reopened.

**Closed as completed by meetmandeep** 2021-06-17 18:06 UTC
