### ISSUE TITLE
Improve Sign up & My Account

### ISSUE THREAD

**Issue by hshimanshusharma** [vanjarosoftware/Vanjaro.Platform#886] opened 2021-03-03 12:15 UTC
Add Sign in & out functionality into Sign up & My Account Block
Remove  Sign In & out  block 
Rename **Sign up & My Account** from **Sign in & My Account**

**Comment by meetmandeep** [comment] 2021-03-05 05:22
Duplicate of #869

**Closed by meetmandeep** 2021-03-05 05:22 UTC
Labels: Area: Backend, Area: Frontend, Enhancement
