### ISSUE TITLE
Sometimes sorting the pages opens blocks UI

### ISSUE THREAD

**Issue by Gaganbird** [vanjarosoftware/Vanjaro.Platform#288] opened 2020-11-03 11:18 UTC
![image](https://user-images.githubusercontent.com/52308516/97978862-34344a80-1df4-11eb-9145-46116fd91a85.png)
![image](https://user-images.githubusercontent.com/52308516/97978987-6d6cba80-1df4-11eb-8617-e8b4ce3c66d8.png)

**Comment by hshimanshusharma** [comment] 2020-12-29 12:01
@Gaganbird  the issue is not duplicating, maybe it's fixed confirm and close the issue

**Closed as completed** 2021-01-04 20:18 UTC
Labels: Cannot Reproduce
