### ISSUE TITLE
Unable to resize icon from styling tab

### ISSUE THREAD

**Issue by pankajmandeeps** [vanjarosoftware/Vanjaro.Platform#602] opened 2021-01-25 13:03 UTC
![image](https://user-images.githubusercontent.com/70753387/105709419-b20f7a00-5f3b-11eb-8abe-996faac3c6bc.png)

**Comment by Gaganbird** [comment] 2021-01-28 13:26
Duplicate of #591

**Closed as completed by Gaganbird** 2021-01-28 13:26 UTC
Labels: Bug, Release: Minor, Priority: Medium, Area: Frontend
