### ISSUE TITLE
can't add or move existing instance of DNN module to a Vanjaro page

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#926] opened 2021-03-09 14:06 UTC
Once a DNN page is converted to Vanjaro, there's no way to bring in any more pre-existing DNN modules from other DNN pages. An existing DNN module instance can't be moved to Vanjaro, nor can it be added to Vanjaro. This capability is important when migrating existing pages.

**Comment by meetmandeep** [comment] 2021-03-09 20:51
This is a duplicate of #371

**Closed as completed by meetmandeep** 2021-03-09 20:51 UTC
Labels: wontfix
