### ISSUE TITLE
Image editor doesn't edit

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1342] opened 2021-05-27 19:54 UTC
**Product & Version**
RC2

**Describe the bug**
The image editor makes changes in the preview but after 'apply' the only option (I know of) is to click the close-button and see that nothing has changed.

**To Reproduce**
1. add image block
2. add image
3. click pencil button
4. click square
5. apply below
6. apply right top
7. and....close(?)

**Expected behavior**
After 'apply' right top the image has been changed and the popup closes

**Current behavior**
See 'to reproduce'

**Screenshots**
![image](https://user-images.githubusercontent.com/9091997/119888754-0c463900-bf36-11eb-8350-cade4da279e5.png)

**Comment by meetmandeep** [comment] 2021-05-27 21:29
I'm unable to reproduce the issue. I followed your steps. After step #6, when I click "Apply" on top right, the popup closes automatically, page shows "Optimizing Images" and I see the edited image on the page. 

I'm seeing the expected behavior. Do you get a console error when you click on "Apply" on top right?

**Comment by scottw12** [comment] 2021-05-28 01:09
I followed and could not reproduce the issue either.

**Comment by Tychodewaard** [comment] 2021-05-28 07:15
In Chrome console:
An invalid form control with name='category' is not focusable.
An invalid form control with name='name' is not focusable.

Not sure whether it is relevant but the RC2 is an upgrade from RC1.

**Comment by meetmandeep** [comment] 2021-05-31 04:21
@Tychodewaard Can you create a blank page (with nothing on it. No Global Blocks). Add an image block and edit the image with image editor. Let me know if issue persists. Thanks

**Comment by Tychodewaard** [comment] 2021-05-31 07:29
The issue persists.
- cropping to a square gives me the correct preview in the popup
- After apply bottom, I click apply right top.
- I get optimizing images and refresh.
- the popup is still openb and preview is still ok but the actual image on the page is still the old one.
- In the file manager I do see the cropped image. So the function somewhat worked but doesn't get applied to the right spot.

**Comment by Tychodewaard** [comment] 2021-06-09 07:19
Just to be complete: a video of the issue on https://www.youtube.com/watch?v=9LU6LgJrrfc

**Comment by Gaganbird** [comment] 2021-06-14 12:42
It has been fixed in #1305

**Closed as completed by Gaganbird** 2021-06-14 12:42 UTC
Labels: Cannot Reproduce
